spring:
  application:
    name: morse

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: bW9yc2Vfc3R1ZHlfYmVzdF9hcHBsaWNhdGlvbgo=
    #morse_study_best_application를 암호화한 base64 기반 jwt 비밀키입니다.



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.200.186.103:3306/morse_test
    username: morse_admin
    password: morse12

  sql:
    init:
      mode: always

  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bomilee.dev@gmail.com
    password: bmsygblljwjgnsaw
    properties:
      mail:
        smtp:
          starttls:
            enable: true

#  main:
#    allow-bean-definition-overriding: true